### ISSUE TITLE
using "thing.find_or_create_property" results in an error if the property does not exist

### ISSUE THREAD

**Issue by WoMeijerPhD** [datacentricdesign/dcd-sdk-python#8]
When the example code is run the first time, the following error gets printed to the terminal:

```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): dwd.tudelft.nl:443
DEBUG:urllib3.connectionpool:https://dwd.tudelft.nl:443 "GET /bucket/api/things/dcd:things:a5c629a3-c9be-437e-b279-f33a0b879450 HTTP/1.1" 200 3408
INFO:dcd:things:a5c629a3-c9be-437e-b279-f33a0b879450:[http] Connection successful
DEBUG:dcd:things:a5c629a3-c9be-437e-b279-f33a0b879450:[mqtt] Initialising connection.
{'id': 'dcd:things:a5c629a3-c9be-437e-b279-f33a0b879450', 'name': 'My Test Thing', 'description': 'A Thing to test!', 'type': 'GENERIC', 'properties': [{'id': 'dcd:properties:bcd71ce4-c91b-4295-a86a-76d0893afa55', 'name': 'IP Address', 'description': 'Local and external IP address', 'typeId': 'IP_ADDRESS', 'thing_id': 'dcd:things:a5c629a3-c9be-437e-b279-f33a0b879450'}, {'id': 'dcd:properties:ae8c49bf-a5b0-47c1-a038-73552c68f0de', 'name': 'Network Status', 'description': 'Status of an MQTT connection.', 'typeId': 'MQTT_STATUS', 'thing_id': 'dcd:things:a5c629a3-c9be-437e-b279-f33a0b879450'}, {'id': 'dcd:properties:7f247b70-db5a-4cdc-86ae-dd57e275501e', 'name': 'My Python Accelerometer', 'description': 'Acceleration force that is applied to a device on all three physical axes x, y and z, including the force of gravity.', 'typeId': 'ACCELEROMETER', 'thing_id': 'dcd:things:a5c629a3-c9be-437e-b279-f33a0b879450'}, {'id': 'dcd:properties:a1be85dd-5c64-48b0-9d0b-02463c19d791', 'name': 'Random Accelerometer', 'description': 'Acceleration force that is applied to a device on all three physical axes x, y and z, including the force of gravity.', 'typeId': 'ACCELEROMETER', 'thing_id': 'dcd:things:a5c629a3-c9be-437e-b279-f33a0b879450'}], 'createdAt': '2021-03-12T10:10:18.402Z', 'updatedAt': '2021-03-12T10:42:21.667Z'}
DEBUG:dcd:things:a5c629a3-c9be-437e-b279-f33a0b879450:Property new test accel was not found.
DEBUG:root:DigicertCA exist.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): dwd.tudelft.nl:443
INFO:dcd:things:a5c629a3-c9be-437e-b279-f33a0b879450:[mqtt] MQTT connection successful
DEBUG:dcd:things:a5c629a3-c9be-437e-b279-f33a0b879450:[mqtt] Updating property dcd:properties:bcd71ce4-c91b-4295-a86a-76d0893afa55...
DEBUG:urllib3.connectionpool:https://dwd.tudelft.nl:443 "POST /bucket/api/things/dcd:things:a5c629a3-c9be-437e-b279-f33a0b879450/properties HTTP/1.1" 201 4413
Traceback (most recent call last):
  File "/Users/womeijer/code/bucket/dcd-sdk-python/example.py", line 26, in <module>
    generate_dum_property_values(my_property)
  File "/Users/womeijer/code/bucket/dcd-sdk-python/example.py", line 23, in generate_dum_property_values
    the_property.update_values(values)
  File "/Users/womeijer/code/bucket/dcd-sdk-python/dcd/bucket/properties/property.py", line 97, in update_values
    self.thing.update_property(self, file_name)
  File "/Users/womeijer/code/bucket/dcd-sdk-python/dcd/bucket/thing_http.py", line 122, in update_property
    self.logger.debug("[http] " + str(prop.to_json()))
  File "/Users/womeijer/code/bucket/dcd-sdk-python/dcd/bucket/properties/property.py", line 65, in to_json
    if self.thing is not None and self.thing.id is not None:
AttributeError: 'ThingHTTP' object has no attribute 'id'
```

## poking around

If I put in a breakpoint, I see that the new property gets a "thing" with it's own "thing" which then contains the id:
![image](https://user-images.githubusercontent.com/79914012/116984409-808d1400-accb-11eb-9304-cc79bf4d9c47.png)

## what to take a look at

I am going to use breakpoints to try and get to the bottom of how the property is assigned a "thing" and why this goes wrong for a newly created property

**Comment by jackybourgeois** [comment]
Thanks for fixing that one!
